<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;


class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data =[
            [
                'role_id' => '5',
                'username' => 'dewilestari',
                'email' => 'dewilestari@gmail.com',
                'password' => Hash::make('123456'),
                'name' => 'Dewi Lestari',
                'phone' => '081234564849',
                'picture' => '',
                'auth_token' => '',
                'device_token' => '',
                'created_at' => '2024-11-13 05:17:44',
                'updated_at' => '2024-11-13 05:17:44',
            ],
            [
                'role_id' => '5',
                'username' => 'aimandestra',
                'email' => 'aimandestra123@gmail.com',
                'password' => Hash::make('234567'),
                'name' => 'Aiman Destra Jubran',
                'phone' => '0813788283727',
                'picture' => '',
                'auth_token' => '',
                'device_token' => '',
                'created_at' => '2024-11-13 05:19:43',
                'updated_at' => '2024-11-13 05:19:43',
            ],
            [
                'role_id' => '1',
                'username' => 'rakha123',
                'email' => 'rakha123@gmail.com',
                'password' => Hash::make('789090'),
                'name' => 'Ryan Rakha Nugraha',
                'phone' => '082726262527',
                'picture' => '',
                'auth_token' => '',
                'device_token' => '',
                'created_at' => '2024-11-13 05:19:43',
                'updated_at' => '2024-11-13 05:19:43',
            ],
            [
                'role_id' => '4',
                'username' => 'bagus123',
                'email' => 'baguschyo@gmail.com',
                'password' => Hash::make('123456'),
                'name' => 'Bagus Cahyo Hardono',
                'phone' => '083363742922',
                'picture' => '',
                'auth_token' => '',
                'device_token' => '',
                'created_at' => '2024-11-16 13:53:49',
                'updated_at' => '2024-11-16 13:53:49',
            ],
            [
                'role_id' => '5',
                'username' => 'rizki456',
                'email' => 'rizki@gmail.com',
                'password' => Hash::make('123456'),
                'name' => 'Rizki Pratama',
                'phone' => '083363742923',
                'picture' => '',
                'auth_token' => '',
                'device_token' => '',
                'created_at' => '2024-11-16 13:55:26',
                'updated_at' => '2024-11-16 13:55:26',
            ],
            [
                'role_id' => '5',
                'username' => 'siti789',
                'email' => 'siti@gmail.com',
                'password' => Hash::make('123456'),
                'name' => 'Siti Aisyah',
                'phone' => '083363742924',
                'picture' => '',
                'auth_token' => '',
                'device_token' => '',
                'created_at' => '2024-11-16 13:55:26',
                'updated_at' => '2024-11-16 13:55:26',
            ],
            [
                'role_id' => '5',
                'username' => 'yusuf321',
                'email' => 'yusuf@gmail.com',
                'password' => Hash::make('123456'),
                'name' => 'Yusuf Maulana',
                'phone' => '083363742925',
                'picture' => '',
                'auth_token' => '',
                'device_token' => '',
                'created_at' => '2024-11-16 13:55:26',
                'updated_at' => '2024-11-16 13:55:26',
            ],
            [
                'role_id' => '5',
                'username' => 'ani654',
                'email' => 'ani@gmail.com',
                'password' => Hash::make('123456'),
                'name' => 'Ani Lestari',
                'phone' => '083363742926',
                'picture' => '',
                'auth_token' => '',
                'device_token' => '',
                'created_at' => '2024-11-16 13:55:26',
                'updated_at' => '2024-11-16 13:55:26',
            ],
            [
                'role_id' => '5',
                'username' => 'budi123',
                'email' => 'budi@gmail.com',
                'password' => Hash::make('123456'),
                'name' => 'Budi Santoso',
                'phone' => '083363742927',
                'picture' => '',
                'auth_token' => '',
                'device_token' => '',
                'created_at' => '2024-11-16 13:55:26',
                'updated_at' => '2024-11-16 13:55:26',
            ],
            [
                'role_id' => '5',
                'username' => 'ina456',
                'email' => 'ina@gmail.com',
                'password' => Hash::make('123456'),
                'name' => 'Ina Kartika',
                'phone' => '083363742928',
                'picture' => '',
                'auth_token' => '',
                'device_token' => '',
                'created_at' => '2024-11-16 13:55:26',
                'updated_at' => '2024-11-16 13:55:26',
            ],
            [
                'role_id' => '5',
                'username' => 'agus789',
                'email' => 'agus@gmail.com',
                'password' => Hash::make('123456'),
                'name' => 'Agus Wijaya',
                'phone' => '083363742929',
                'picture' => '',
                'auth_token' => '',
                'device_token' => '',
                'created_at' => '2024-11-16 13:55:26',
                'updated_at' => '2024-11-16 13:55:26',
            ],
            [
                'role_id' => '5',
                'username' => 'dina321',
                'email' => 'dina@gmail.com',
                'password' => Hash::make('123456'),
                'name' => 'Dina Syafitri',
                'phone' => '083363742930',
                'picture' => '',
                'auth_token' => '',
                'device_token' => '',
                'created_at' => '2024-11-16 13:55:26',
                'updated_at' => '2024-11-16 13:55:26',
            ],
            [
                'role_id' => '5',
                'username' => 'andi654',
                'email' => 'andi@gmail.com',
                'password' => Hash::make('123456'),
                'name' => 'Andi Setiawan',
                'phone' => '083363742931',
                'picture' => '',
                'auth_token' => '',
                'device_token' => '',
                'created_at' => '2024-11-16 13:55:26',
                'updated_at' => '2024-11-16 13:55:26',
            ],
            [
                'role_id' => '5',
                'username' => 'linda123',
                'email' => 'linda@gmail.com',
                'password' => Hash::make('123456'),
                'name' => 'Linda Susanti',
                'phone' => '083363742932',
                'picture' => '',
                'auth_token' => '',
                'device_token' => '',
                'created_at' => '2024-11-16 13:55:26',
                'updated_at' => '2024-11-16 13:55:26',
            ],
        ];
        DB::table('m_user')->insert($data);
    }
}
